base:
  project: insurance-price-prediction
  random_state: 180
  target_data: expenses

data_source: 
  local_data: data_given/insurance_updated.csv

load_data: 
  raw_data_csv: data/raw/insurance_updated.csv

split_data:
  train_path: data/processed/train_insurance.csv
  test_path: data/processed/test_insurance.csv
  split_ratio: 0.25



estimators: 
  GradientBoostingRegressor:
  - loss: ls
  - learning_rate: 0.1
  - n_estimators: 100
  - subsample: 1.0
  - criterion: friedman_mse
  - min_samples_split: 2
  - min_samples_leaf: 1
  - min_weight_fraction_leaf: 0.0
  - max_depth: 3
  - min_impurity_decrease: 0.0
  - min_impurity_split: None
  - init: None
  - max_features: None
  - alpha: 0.9
  - verbose: 0
  - max_leaf_nodes: None
  - warm_start: False
  - validation_fraction: 0.1
  - n_iter_no_change: None
  - tol: 0.0001
  - ccp_alpha: 0.0

model_dirs: saved_models
