base:
  project: insurance-price-prediction
  random_state: 180
  target_data: expenses

data_source: 
  local_data: data_given/insurance_updated.csv

load_data: 
  raw_data_csv: data/raw/insurance_updated.csv

split_data:
  train_path: data/processed/train_insurance.csv
  test_path: data/processed/test_insurance.csv
  split_ratio: 0.25



estimators: 
  GradientBoostingRegressor:
    params:
      learning_rate: 0.1033
      n_estimators: 100
      alpha: 0.99
      verbose: 0
      validation_fraction: 0.000001
      tol: 0.0001
      ccp_alpha: 0.1

reports:
  scores: reports/scores.json
  params: reports/params.json



model_dirs: saved_models
